account/urls.py
from django.urls.conf import path
from account import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

crud/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',blog.views.main,name='main'), #제일 첫 화면 메인
    path('detail/<str:id>', blog.views.detail, name="detail"), # 디테일페이지 경로(id 값에 따라서 상세페이지가 다르게 보임 )
    path('write/create/', blog.views.create, name="create"), #글 작성페이지 경로 (forms를 사용하여 함수를 따로 작성하여 create되게)
    path('edit/<str:id>',blog.views.edit,name="edit"), #수정페이지 경로 (디테일과 마찬가지로 글 id값에 따라 다르게 보여아함)
    path('delete/<str:id>',blog.views.delete,name="delete"), #삭제페이지 (수정페이지와 동일)
    path('hashtag/',blog.views.hashtagform,name="hashtag"), #해쉬태그 추가하는 페이지
    path('search/<int:hashtag_id>',blog.views.search,name="search"), #해쉬태그 검색 페이지
    path('account/',include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser #CustomerUser를 만들렬면 
# Create your models here.
class CustomUser(AbstractUser): #1:1 관계
    age = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)

blog/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Blog(models.Model): #
    title = models.CharField(max_length=200) #글 제목 
    writer = models.CharField(max_length=100,default='작성자를 적어주세요.') #글 작성자
    pub_date = models.DateTimeField('data published') #글 쓰는 시각
    content = models.TextField() #글 내용 (글자수 제한없이 )
    hashtags = models.ManyToManyField('Hashtag',blank=True)
    image = models.ImageField(upload_to='images/',blank=True)

    def __str__(self): #글 제목을 자신으로 받아서 넣음
        return self.title

# 댓글 기능 클래스 
class Comment(models.Model): 
    def __str__(self):
        return self.text
    
    post_id=models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    text=models.CharField(max_length=50)

# 해쉬태그 기능 클래스
class Hashtag(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name

account/forms.py
# CustomUser 폼을 따로 만들어서 여러가지를 입력 받을 수 있게
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class RegisterForm(UserCreationForm): #UserCreationForm 상속 받아 
    class Meta:
        model = CustomUser #지정한 값으로 변경해서 model 사용
        fields = ['username','password1','password2','age','address']

blog/forms.py
from django import forms
from django.forms import models
from .models import Blog,Comment, Hashtag

class PostForm(forms.ModelForm):
    class Meta:
        model = Blog #Blog 모델을 참조해서 model을 만듬 
        fields = ['title', 'writer','content','image','hashtags'] #모델 값은 이러함.

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm # 로그인, 회원가입 폼 
from .forms import RegisterForm
#회원가입 
def signup(request):
    if request.method == 'POST': #Post 방식 
        form = RegisterForm(request.POST)
        if form.is_valid(): #유효성 검사 
            user = form.save()
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, 'account/signup.html', {'form':form})
    else: #get 방식 
        form = RegisterForm()
        return render(request, 'account/signup.html', {'form':form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, 'account/login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'account/login.html', {'form': form})

def logout(request):
    auth.logout(request)
    return redirect('main')

blog/views.py
from django.http import request
from django.shortcuts import redirect, render,get_object_or_404 
from django.utils import timezone
from .forms import PostForm,CommentForm,HashtagForm
from .models import Blog,Hashtag
# Create your views here.

#메인페이지
def main(request):
    blogs = Blog.objects.all() #Blog 객체의 값들을 모두 가져옴
    hashtags = Hashtag.objects.all()
    return render(request, 'blog/main.html', {'blogs':blogs,'hashtags':hashtags})

# 글 작성 페이지 
def write(request):
    return render(request, 'blog/write.html')

#글 작성 함수
def create(request):
    if request.method == 'POST': #POST 메소드 방식인지 확인 
        form = PostForm(request.POST,request.FILES) #POST방식으로 요청받은 form을 변수에 저장
        if form.is_valid(): #유효한지 검사
            form=form.save(commit=False) 
            form.pub_date=timezone.now()
            form.save()
            return redirect('main') #form을 잘 입력했으면 main페이지로 이동 
    else: #유효하지 않으면 다시 검사해서 
        form=PostForm
        return render(request,'blog/write.html',{'form':form}) #다시 작성하게함

#수정페이지 (write페이지와 동일)
def edit(request,id): 
    post = get_object_or_404(Blog,id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post) #수정해야 할 글의 id를 함수에게 전달
        if form.is_valid():
            form.save(commit=False)
            form.save()
            form.save_m2m()
            return redirect('detail',id)
    else:
        form=PostForm(instance=post)
        return render(request, 'blog/edit.html',{'form':form})

#삭제페이지
def delete(request, id):
    delete_blog=Blog.objects.get(id=id) #삭제할 글의 id를 가져와
    delete_blog.delete() # 삭제
    return redirect('main') #메인페이지로 이동 

#디테일 페이지 + 댓글
def detail(request, id):
    blog = get_object_or_404(Blog, id = id) 
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post_id=blog
            comment.text=form.cleaned_data['text']
            comment.save()
            return redirect('detail',id)
    else:
        form = CommentForm()
        return render(request, 'blog/detail.html', {'blog':blog,'form':form})

#해쉬태그 함수
def hashtagform(request,hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST,instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message= "이미 존재하는 해시태그 입니다."
                return render(request, 'blog/hashtag.html',{'form':form,'error_message':error_message})
            else:
                hashtag.name=form.cleaned_data['name']
                hashtag.save()
            return redirect('main')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'blog/hashtag.html',{'form':form})

def search(request, hashtag_id):
        hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
        return render(request, 'blog/search.html', {'hashtag':hashtag})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>My Notice Board</title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'main' %}">LikeLion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main' %}">Home</a></li>
                        {% if user.is_active %} <!-- 로그인 되었을 때 -->
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'create' %}">Write</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'hashtag' %}">Add Hashtag</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">로그아웃</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4">{{ user.username }}님 안녕하세요.</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login' %}">로그인</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'signup' %}">회원 가입</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% block header %}
        {% endblock %}

        <!-- Main Content-->
        {% block content %}
        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; LikeLion at SKHU 9th</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/script.js' %}"></script>
    </body>
</html>

templates/blog/detail.html
{% extends 'base.html' %} 
{% block header %}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="site-heading">
                  <h1>My Detail Page</h1>
                  <span class="subheading">디테일 페이지 입니다.</span>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}
{% block content %} 
{% load static %}
<div class="container">
    <div class="post-preview">
        <a href="post.html">
            <h2 class="post-title">{{ blog.title }}</h2>
            <h3 class="post-subtitle">{{ blog.content }}</h3>
        </a>
        <p class="post-meta">
            Posted by
            <a href="#!">{{ blog.writer }}</a>
            {{ blog.pub_date }}
        </p>
        <!--이미지 구현-->
        {% if blog.image %}
            <img src="{{ blog.image.url }}" width="250" height="250" alt="image error">
        {% endif %}
        <br>
        <br>
        <!--해시태그 구현-->
        {% for hashtag in blog.hashtags.all %}
            <span>{{ hashtag.name }}</span>
        {% endfor %}     
        <!--댓글 구현-->
        {% for comment in blog.comments.all %}
            <p>{{comment.text}}</p>
        {% endfor %}
        <form method="POST" action="{% url 'detail' blog.id %}">
            {% csrf_token %}
            <p>{{ form.as_p }}</p>
            <input type="submit" value="submit">
        </form>
        <br>
        <a class="btn btn-primary float" href="{% url 'edit' blog.id %}"> 수정하기 →</a>
        <a class="btn btn-primary float" href="{% url 'delete' blog.id %}"> 삭제하기 →</a>
    </div>
</div>

{% endblock %}

templates/blog/edit.html
{% extends 'base.html' %} 
{% block header %}
  <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>My Edit Page</h1>
                    <span class="subheading">게시글 수정 페이지입니다.</span>
                </div>
            </div>
        </div>
    </div>
  </header>
  {% endblock %}
    
  {% block content %} 
  {% load static %}
  <div class="container">
    <body style="text-align: center">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">Submit</button>
      </form>
    </body>
  </div>

{% endblock %}

templates/blog/hashtag.html
{% extends 'base.html' %} 
{% block header %}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="site-heading">
                  <h1>My Hashtag Page</h1>
                  <span class="subheading">해시태그를 추가하는 페이지입니다.</span>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}

{% block content %} 
{% load static %}
<div class="container">
  <body style="text-align: center">
    {{ error_message }}
    <form method="POST">
      {% csrf_token %}
      <table>
          {{form.as_table}}
      </table>
      <button type="submit">Submit</button>
    </form>
  </body>
</div>

{% endblock %}

templates/blog/main.html
{% extends 'base.html' %} 
{% block header %}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="site-heading">
                  <h1>My Board Page</h1>
                  <span class="subheading">메인페이지 입니다.</span>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}

{% block content %} 
{% load static %} 
<div class="container">
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
          Search Hasttag
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          {% for hashtag in hashtags.all %}
          <a class="dropdown-item" href="{% url 'search' hashtag.id %}">{{ hashtag.name }} </a>
          {% endfor %}
        </ul>
      </div>
</div>
  <!-- Post preview-->
  {% for blog in blogs %}
<div class="container">
    <div class="post-preview">
        <a href="{% url 'detail' blog.id %}">
            <h2 class="post-title">{{ blog.title }}</h2>
            <h3 class="post-subtitle">{{ blog.content }}</h3>
        </a>
        <p class="post-meta">
            Posted by
            {{ blog.writer }}</a>
            {{ blog.pub_date }}
        </p>
        <a class="btn btn-primary float" href="{% url 'detail' blog.id %}"> 더보기 →</a>
    </div>
</div>


{% endfor %} 

{% endblock %}

templates/blog/search.html
{% extends 'base.html' %} 
{% block header %}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="site-heading">
                  <h1>{{ hashtag }}가 있는 게시글 목록</h1>
                  <span class="subheading">해시태그 검색한 게시글 목록이 있는 페이지</span>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}

{% block content %} 
{% load static %} 
  <!-- Post preview-->
  {% for blog in hashtag.blog_set.all %}
<div class="container">
    <div class="post-preview">
        <a href="{% url 'detail' blog.id %}">
            <h2 class="post-title">{{ blog.title }}</h2>
            <h3 class="post-subtitle">{{ blog.content }}</h3>
        </a>
        <p class="post-meta">
            Posted by
            {{ blog.writer }}</a>
            {{ blog.pub_date }}
        </p>
        <a class="btn btn-primary float" href="{% url 'detail' blog.id %}"> 더보기 →</a>
    </div>
</div>


{% endfor %} 

{% endblock %}

templates/blog/write.html
{% extends 'base.html' %} 

{% block header %}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="site-heading">
                  <h1>My Write Page</h1>
                  <span class="subheading">새로운 게시글을 작성하세요</span>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}

{% block content %} 
{% load static %}
<div class="container">
  <body style="text-align: center">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
          {{form.as_table}}
      </table>
      <button type="submit">Submit</button>
    </form>
  </body>
</div> 

{% endblock %}